Restructuring, Adding Import and Export
derBroBro/aws-role-editor pull request #5
Opened 2017-03-19 11:09 UTC by mwiora

Hi Malte! :)

I've restructured your code and added an import and export functionality.
It would be great if you could review my code changes.

Cheers,
Matthias

2017-03-19 11:50 UTC, derBroBro commented
Hello Matthias,

thank you for the large update and the new import / export function. I try to check the code this week. :-)

Best Malte

2017-03-19 15:49 UTC, mwiora commented
Hi Malte,

thanks! :)
I just added some s3-capabilities (storing the user-role-cookie-content).

Cheers,
Matthias

2017-03-24 14:37 UTC, derBroBro commented
Hi Matthias,

I added some comments.
It would be greate if we can try to keep the PR as small as possible and create new ones if needed. Each should only contain one feature. Specialy the S3 option is such a new feature which would great to discuss in an extra scope.

Best Malte

2017-03-24 14:37 UTC, derBroBro requested changes
Hi Matthias,

I added some comments.
It would be greate if we can try to keep the PR as small as possible and create new ones if needed. Each should only contain one feature. Specialy the S3 option is such a new feature which would great to discuss in an extra scope.

Best Malte

2017-03-24 14:37 UTC, derBroBro commented on LICENSE.txt
> +Copyright (c) 2017 Matthias R. Wiora
Unusual, we can add a part to the readme.md who contributed which feature.

2017-03-24 14:37 UTC, derBroBro commented on README.md
> +[![Code Climate](https://codeclimate.com/github/mwiora/aws-role-editor/badges/gpa.svg)](https://codeclimate.com/github/mwiora/aws-role-editor)
Needs to be set to this target project.

2017-03-24 14:37 UTC, derBroBro commented on README.md
> +![Editor](https://raw.githubusercontent.com/mwiora/aws-role-editor/master/res/screen02.png "AWS Role Editor")
Needs to be set to this target project.

2017-03-24 14:37 UTC, derBroBro commented on README.md
> +![AWS Console](https://raw.githubusercontent.com/mwiora/aws-role-editor/master/res/screen01.png "AWS Role Editor")
Needs to be set to this target project.

2017-03-24 14:37 UTC, derBroBro commented on js/popup.js
> +    function getConfigFromS3(accessKeyId, secretAccessKey, region, s3bucket, s3key) {
I tried to keep such information out of the extension to keep it lean for security reasons.
Mostly the enterprises I know, have many more then five accounts.
An option would to provide a "import from URL" function. Here a presigned S3-URL can be provided which is much more secure then create a whole IAM user.
Also a GIST or other site can be used.

2019-04-11 17:54 UTC, closed without merging